package com.EntityModel;
// Generated Sep 24, 2019 3:51:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String emailAddress;
     private String password;
     private Date dateOfBarth;
     private String contactNo;
     private String gender;

    public Customer() {
    }

    public Customer(String userName, String emailAddress, String password, Date dateOfBarth, String contactNo, String gender) {
       this.userName = userName;
       this.emailAddress = emailAddress;
       this.password = password;
       this.dateOfBarth = dateOfBarth;
       this.contactNo = contactNo;
       this.gender = gender;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateOfBarth() {
        return this.dateOfBarth;
    }
    
    public void setDateOfBarth(Date dateOfBarth) {
        this.dateOfBarth = dateOfBarth;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


