package com.EntityModel;
// Generated Sep 24, 2019 3:51:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer proId;
     private SubCategory subCategory;
     private String proName;
     private int proQuantity;
     private double proPrice;
     private String proUrl;
     private String proDsc;
     private Set orderDetailses = new HashSet(0);
     private Set proOrders = new HashSet(0);

    public Product() {
    }

	
    public Product(SubCategory subCategory, String proName, int proQuantity, double proPrice, String proUrl, String proDsc) {
        this.subCategory = subCategory;
        this.proName = proName;
        this.proQuantity = proQuantity;
        this.proPrice = proPrice;
        this.proUrl = proUrl;
        this.proDsc = proDsc;
    }
    public Product(SubCategory subCategory, String proName, int proQuantity, double proPrice, String proUrl, String proDsc, Set orderDetailses, Set proOrders) {
       this.subCategory = subCategory;
       this.proName = proName;
       this.proQuantity = proQuantity;
       this.proPrice = proPrice;
       this.proUrl = proUrl;
       this.proDsc = proDsc;
       this.orderDetailses = orderDetailses;
       this.proOrders = proOrders;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public int getProQuantity() {
        return this.proQuantity;
    }
    
    public void setProQuantity(int proQuantity) {
        this.proQuantity = proQuantity;
    }
    public double getProPrice() {
        return this.proPrice;
    }
    
    public void setProPrice(double proPrice) {
        this.proPrice = proPrice;
    }
    public String getProUrl() {
        return this.proUrl;
    }
    
    public void setProUrl(String proUrl) {
        this.proUrl = proUrl;
    }
    public String getProDsc() {
        return this.proDsc;
    }
    
    public void setProDsc(String proDsc) {
        this.proDsc = proDsc;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }
    public Set getProOrders() {
        return this.proOrders;
    }
    
    public void setProOrders(Set proOrders) {
        this.proOrders = proOrders;
    }




}


