package com.EntityModel;
// Generated Sep 24, 2019 3:51:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProOrder generated by hbm2java
 */
public class ProOrder  implements java.io.Serializable {


     private Integer ordId;
     private DeliveryCost deliveryCost;
     private Product product;
     private ShopeUse shopeUse;
     private Date ordDate;
     private int ordQty;
     private double totalPrice;
     private String ordStatus;
     private Set orderDetailses = new HashSet(0);

    public ProOrder() {
    }

	
    public ProOrder(DeliveryCost deliveryCost, Product product, ShopeUse shopeUse, Date ordDate, int ordQty, double totalPrice, String ordStatus) {
        this.deliveryCost = deliveryCost;
        this.product = product;
        this.shopeUse = shopeUse;
        this.ordDate = ordDate;
        this.ordQty = ordQty;
        this.totalPrice = totalPrice;
        this.ordStatus = ordStatus;
    }
    public ProOrder(DeliveryCost deliveryCost, Product product, ShopeUse shopeUse, Date ordDate, int ordQty, double totalPrice, String ordStatus, Set orderDetailses) {
       this.deliveryCost = deliveryCost;
       this.product = product;
       this.shopeUse = shopeUse;
       this.ordDate = ordDate;
       this.ordQty = ordQty;
       this.totalPrice = totalPrice;
       this.ordStatus = ordStatus;
       this.orderDetailses = orderDetailses;
    }
   
    public Integer getOrdId() {
        return this.ordId;
    }
    
    public void setOrdId(Integer ordId) {
        this.ordId = ordId;
    }
    public DeliveryCost getDeliveryCost() {
        return this.deliveryCost;
    }
    
    public void setDeliveryCost(DeliveryCost deliveryCost) {
        this.deliveryCost = deliveryCost;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public ShopeUse getShopeUse() {
        return this.shopeUse;
    }
    
    public void setShopeUse(ShopeUse shopeUse) {
        this.shopeUse = shopeUse;
    }
    public Date getOrdDate() {
        return this.ordDate;
    }
    
    public void setOrdDate(Date ordDate) {
        this.ordDate = ordDate;
    }
    public int getOrdQty() {
        return this.ordQty;
    }
    
    public void setOrdQty(int ordQty) {
        this.ordQty = ordQty;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getOrdStatus() {
        return this.ordStatus;
    }
    
    public void setOrdStatus(String ordStatus) {
        this.ordStatus = ordStatus;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


